### ISSUE TITLE
[TODO] geOrchestra console API manager

### ISSUE THREAD

**Issue by jeanmi151** [georchestra/geo-utils#1]
In order to pilot user/org/roles process from scripts to automate as much as possible huge amount of modifications :

- [x] get users list with filter or not
- [x] get roles list with filter or not
- [x] get orgs list with filter or not
- [x] create user https://github.com/georchestra/geo-utils/commit/6965434e9fb078d1fb91e654f579c334944b0112 
- [x] update user
- [x] delete user https://github.com/georchestra/geo-utils/commit/392d1b545e65dd1886e09fc23041708bf9ff4555 
- [x] create org https://github.com/georchestra/geo-utils/commit/392d1b545e65dd1886e09fc23041708bf9ff4555 
- [x] delete org https://github.com/georchestra/geo-utils/commit/392d1b545e65dd1886e09fc23041708bf9ff4555
- [ ] update org
- [x] create role https://github.com/georchestra/geo-utils/commit/7f6f75b58b73e342618296d150cab57db072ef46
- [ ] update role's user https://github.com/georchestra/geo-utils/commit/7f6f75b58b73e342618296d150cab57db072ef46
- [ ] update role
- [ ] delete role
- [ ] use filter for get functions https://github.com/georchestra/geo-utils/blob/7505f99d8f44915a90b4f72613da0143dc3bf694/console/console.py#L35
