### ISSUE TITLE
[TODO] improve functionality of gn api

### ISSUE THREAD

**Issue by jeanmi151** [georchestra/geo-utils#2]
I would like to add few functionalities for gn_api in here : https://github.com/georchestra/geo-utils/blob/main/meta_apis/ask_gn_api.py

- [ ] add thesaurus, from file, url - started https://github.com/georchestra/geo-utils/blob/main/meta_apis/ask_gn_api.py#L96 
- [x] get thesaurus https://github.com/georchestra/geo-utils/commit/d33f33af667c38d1fde7cc349c70ff4dcd8cc6dc
- [x] delete thesaurus https://github.com/georchestra/geo-utils/commit/901f27fe7faaa1f3f7af0f69a1f4abc72bbb863c and https://github.com/georchestra/geo-utils/commit/d33f33af667c38d1fde7cc349c70ff4dcd8cc6dc
- [ ] get xml metadata
- [ ] update metadata
- [ ] upload file linked to metadata (thumbnail, files)
- [x] https://github.com/georchestra/geo-utils/issues/4 
- [ ] export statistics from here `/geonetwork/srv/fre/admin.console#/reports/` with this URL for example `/geonetwork/srv/api/reports/metadataupdated?_csrf=[...]&dateFrom=2024-09-01&dateTo=2024-09-30&groups=153`
- [ ] get version in here `/geonetwork/srv/api/site`
- [ ] update rights on a metadata (read, write for groups and publish it)
- [x] harvest get list
- [x] harvest make local to catalog
- [ ] harvest active/disable
- [x] implement batch edit "search and replace" https://github.com/georchestra/geo-utils/commit/195461185a14866d25b9a8f7e2b73a89bd3acfd0
- [ ] implement batch edit "XPATH"
- [ ] implement batch edit "Form editing" 
- [x] implement search keyword https://github.com/georchestra/geo-utils/commit/333770e985a9ff2fc26cff4433127bf9c1293159
- [x] bucket search management (list existing buckets, show the content of one bucket, add content and remove to one bucket) https://github.com/georchestra/geo-utils/commit/35c7831d1a53f125fe180540f9717f1d2170a661
- [ ] get gn groups (GET /geonetwork/srv/api/users/groups)
- [ ] get owner of metadata (in search bucket)
- [ ] change ownership of metadata ( PUT /geonetwork/srv/api/records/ownership?bucket=e101&userIdentifier=104&groupIdentifier=0 )
